### ISSUE TITLE
Utils: Missing type for useResizeAware

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#106]
So far, the wonderful [type update](https://github.com/ItsJonQ/g2/pull/101) has been smooth! Really smooth.

The only thing I've noticed so far was that types were missing from `useResizeAware` in `utils`.

This is what the type definition file looks like:

```js
// packages/utils/types/hooks/useResizeAware.d.ts
export {};
//# sourceMappingURL=useResizeAware.d.ts.map
```

This is the original source `js` code:
```js
// packages/utils/src/hooks/useResizeAware.js
export { default as useResizeAware } from 'react-resize-aware';
```

Not sure what might be causing that 🤔

**Comment by ItsJonQ** [comment]
cc'ing @saramarcondes / @sirreal

**Comment by sirreal** [comment]
As far as I can tell, `react-resize-aware` does not have types. Were you getting relevant type information before?

We could add types on DefinitelyTyped for this package or add a type assertion in the module.

**Comment by ItsJonQ** [comment]
> react-resize-aware does not have types

@sirreal Oh!!! Gotcha :) That makes sense! My apologies!

Will close up this issue!

> Were you getting relevant type information before?

I'm not sure 🤔. Previously, I didn't pay attention to certain G2 packages (e.g. `utils`) due to lack of types.
I guess I got excited with the recent magical "automatically generate all the types" update 😊
