### ISSUE TITLE
Missing font size presets option on font size component of typography tools

### ISSUE THREAD

**Issue by jorgefilipecosta** [ItsJonQ/g2#162]
On font size under typography tools https://g2-components.xyz/iframe.html?id=designtools-presentation-typographypanel--default&viewMode=story we should have the option to have font size presets display in a custom select control (where each option shows the font size used). Even if font size presets in the future may not be a common thing we need to be back-compatible with the current font size presets.

![image](https://user-images.githubusercontent.com/11271197/100011947-653be580-2dca-11eb-8360-19079ac1ec60.png)

Current version on WordPress components:

![image](https://user-images.githubusercontent.com/11271197/100012229-d54a6b80-2dca-11eb-9f36-068948f4d45c.png)

**Comment by ItsJonQ** [comment]
Thanks @jorgefilipecosta !!

Related: https://github.com/ItsJonQ/g2/issues/161

**Comment by ItsJonQ** [comment]
The `SelectDropdown` component was recently merged:
https://github.com/ItsJonQ/g2/issues/161

I'm going to see if I can recreate the `FontSizePicker` in G2 to accommodate this use case.
