### ISSUE TITLE
Components: HStack, VStack, ZStack

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#22]
![1 1](https://user-images.githubusercontent.com/2322354/89843073-7592c200-db45-11ea-85a1-a080c86b919f.jpg)
(Source: [Design+Code](https://designcode.io/swiftui-course))

Recently, I started poking around with [Swift UI](https://developer.apple.com/documentation/swiftui). My, what a wonderful language + workflow it has!

One of the main primitives is their `HStack`, `VStack`, and `ZStack` Views (aka. Components).

After playing around with it, I thought they would be a welcomed edition to this library as well.

It looks like I'm not the only one who would like this for React:

https://twitter.com/dan_abramov/status/1286433774641852417

### Flex

We currently have something similar! The [Flex](https://github.com/ItsJonQ/g2/tree/master/packages/components/src/Flex) component. 

The H/V/Z Stack components could use `Flex` as a their base, and sprinkle some adjustments to achieve the desired effects.

### API/Workflow

One of the key things is injecting `Spacer()` (Swift UI) within one of the stacks to help with layout.

We can achieve something similar:

```jsx
<HStack>
  <Text>Hello</Text>
  <Spacer />
  <Button>Next</Button>
</HStack>
```

```jsx
<VStack>
  <View>Top</View>
  <Spacer />
  <View>Bottom</View>
</VStack>
```

```jsx
<ZStack>
  <View>Layer 0</View>
  <View>Layer 1</View>
</ZStack>
```

We'll need to adjust the `<Spacer />` component to perform double duty to work intelligently within one of these Stack components.

`ZStack` will be a very interesting one! :)

**Comment by simison** [comment]
This would make an interesting technical basis for a block: https://github.com/WordPress/gutenberg/issues/24473

**Comment by ItsJonQ** [comment]
Added with this update!
https://github.com/ItsJonQ/g2/commit/2ffa46ca60ae3db79447b6d1650d813fe5ee40d1

**Comment by ItsJonQ** [comment]
Update! Wrote a blog post about it here:
https://g2components.wordpress.com/2020/08/12/creating-smart-layout-components-hstack-vstack-and-zstack/
