### ISSUE TITLE
Add stylelint, set up to use for CSS-in-JS

### ISSUE THREAD

**Issue by ockham** [ItsJonQ/g2#268]
AFAICS, g2 isn't currently using [`stylelint`](https://stylelint.io/). It seems like `stylelint` nowadays supports CSS-in-JS.

In order to prevent bugs like https://github.com/ItsJonQ/g2/issues/266, how about we:
- Add `stylelint`, set it up for CSS-in-JS
- Make sure it's run on pre-commit, and via GitHub Actions on every PR.

**Comment by ItsJonQ** [comment]
@ockham Haii! I just tried this out. I don't think stylelint is works too well with how the CSS-in-JS styles are written.
I'm currently having to disable a lot of rules 😅
