### ISSUE TITLE
Z-Index System

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#30]
In discussing `<ZStack />` with @MichaelArestad , it occurred to us that the library needs some sort of (app-wide) Z-Index system.

Something that acts like a "registry", where zIndex values can be added, and then referenced in code in human  readiable form.

For example:

```
ui.zIndex('modal')
```

and/or maybe

```
ui.zIndex.modal
```

vs. an arbitrary:

```
zIndex: 1000
```

**Comment by ItsJonQ** [comment]
More thoughts on code APIs/workflows.

If we're going to use the `get()` workflow, then maybe something like:

```js
get('zIndexModal');
```

### Fallbacks

For the `get` example above, maybe we can do this:

```js
get('zIndexModal', 999);
```

With the second argument being a fallback.

Same for `ui.`

```js
ui.zIndex('modal', 999)
```

### Autoregister?

If the `zIndex` does not exist in the system... Maybe the **first** time a call is made, example:

```js
ui.zIndex('modal', 999)
```

It auto registers it.

Order of operations:

1. check `zIndex` system for `modal`. Exists? Use. No?...
2. If fallback value... register `modal` with value `999`
3. Return zIndex value of `999`

---

This workflow (above) feels really seamless. A downside would maybe be some unpredictability factors later on as the system scales 🤔

**Comment by MichaelArestad** [comment]
I think I understand. If the "modal" z-index is already used, it uses the 999 instead. If the modal index is already used and a fallback is unspecified, should the fallback be whatever the modal's z-index is plus one?

**Comment by ItsJonQ** [comment]
I added the zIndex system in this update:
https://github.com/ItsJonQ/g2/commit/ea3c56221441c715fa524cc3cdca2230899f8141

Working pretty well :)

> should the fallback be whatever the modal's z-index is plus one?

I think there may be something interesting here...

Could we expand on that, just so I can understand better?

Let's say, `Modal` is registered for `999`.

And it gets used here.
```
// My Custom Modal
ui.zIndex('Modal')
```

And randomly in another component:
```
// My Other Custom Modal
ui.zIndex('Modal')
```

Would the results be `999` and `999`?

or `1000` and `1000`?

or `1000` and `1001`?

**Comment by MichaelArestad** [comment]
I would expect the results to be ModalValue  (999) and ModalValue plus 1 (1000).

This might result in unexpected layering, though. It's also annoying that there can be separate z-index contexts so 999 might still be covered by something with 1.

**Comment by ItsJonQ** [comment]
Maybe something to tinker with, or something we'll see/feel as `ui.zIndex()` gets used more :).

The initial system is built, so that's a start :D

**Comment by MichaelArestad** [comment]
`ui.zIndex('🙌')`

**Comment by ItsJonQ** [comment]
Technically, that works!!! 😂 

```
ui.zIndex('🙌', 900000000000000)
```

**Comment by ItsJonQ** [comment]
Closing this! It's been working well since this update:
https://github.com/ItsJonQ/g2/commit/ea3c56221441c715fa524cc3cdca2230899f8141
