### ISSUE TITLE
Build: Reduce bundle size (Tree shaking)

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#37]
I think there maybe something up with babel... or something. It doesn't look like tree-shaking is working correctly as A LOT of `react-icons` is included in the build.

Do babel builds even tree shake? I have no idea 😂

**Comment by saramarcondes** [comment]
So `babel` has some sort of tree-shaking built in... but only for [lazy components and things like that](https://babeljs.io/blog/2020/05/25/7.10.0#better-tree-shaking-for-react-components-11428httpsgithubcombabelbabelpull11428).

Where tree-shaking really comes in is webpack (from what I understand).

Do you have an example build (how to get the build) that you're looking at @ItsJonQ?

**Comment by ItsJonQ** [comment]
@saramarcondes Thank you for that context!

> Do you have an example build (how to get the build) that you're looking at @ItsJonQ?

Recently, what I've done is I use a new `create-react-app` instance, and add `@wp-g2/components` as a dependency.
I'd think import `Button` or `Modal` or something into the project.

Lastly, I'd run the build and [analyze the bundle](https://create-react-app.dev/docs/analyzing-the-bundle-size/).

I'm not sure if the results I'm seeing are good or not? Haha.
I'd love a second pair of (more experienced) eyes on it though - just to double check :)

**Comment by saramarcondes** [comment]
In that case, I believe tree-shaking is working just fine!

Take these two screenshots for example. The first is from just importing Button from G2. Note that only Button and its related components are imported. Then look at the second, where I've also imported (and used) VStack. Note that it now exists in the build when it did not before.

This means that indeed, tree-shaking is working as expected.

![Captura de Tela 2020-11-12 às 12 03 23](https://user-images.githubusercontent.com/24264157/98990466-59eddd80-24df-11eb-8fca-9c18bb84bb42.png)
![Captura de Tela 2020-11-12 às 12 04 02](https://user-images.githubusercontent.com/24264157/98990476-5d816480-24df-11eb-853f-ec101ce7cec4.png)

**Comment by ItsJonQ** [comment]
Phew! Thank goodness. Thanks for confirming @saramarcondes !!!

Will close this up ❤️
