### ISSUE TITLE
Layout: Grouping/Segmenting controls

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#43]
<img width="279" alt="Screenshot of control clusters with annotations highlighting sections" src="https://user-images.githubusercontent.com/2322354/92016705-bb940d80-ed20-11ea-926a-81efd30961fd.png">

I think we need some components/conventions to make it simple to create cohesive clusters and groupings of controls. In the screenshot above, things are arbitrarily spaced using `<Spacer />`. It works as it follows the grid system, but I feel like it should be even more seamless than that.

Maybe something like this?

```jsx
<FormGroups title="Dimensions">
  <FormGroup label="Width">
    <TextInput />
  </FormGroup>
  <FormGroup label="Height">
    <TextInput />
  </FormGroup>
</FormGroups>
```

Similar to how iOS handles clusters (groups) of controls via `Tables`

<img width="409" alt="Screenshot of iOS Tables from their Human Interface Guidelines" src="https://user-images.githubusercontent.com/2322354/92017107-46750800-ed21-11ea-8b4a-f4bf5ed7561f.png">

https://developer.apple.com/design/human-interface-guidelines/ios/views/tables/

Not only should it handle the typical use-case of `Label      [ TextInput ]`, but it should also accommodate custom UI, like a potential color setting (below):

<img width="273" alt="Screenshot of a color setting from a Global Styles design" src="https://user-images.githubusercontent.com/2322354/92017220-702e2f00-ed21-11ea-9030-e2b23b95ace6.png">

**Comment by jasmussen** [comment]
I just encountered something related to this with rows of swatches in gradients. It's hard to make those rows have the right margin between them, yet survive a scrollbar appearing.

**Comment by ItsJonQ** [comment]
Another source of inspiration to draw from...

Bootstrap's ListGroup:
https://getbootstrap.com/docs/4.0/components/list-group/

**Comment by ItsJonQ** [comment]
Starting to really explore this with a variety of control types and setups:

<img width="500" alt="Screen Shot 2020-09-14 at 1 49 09 PM" src="https://user-images.githubusercontent.com/2322354/93120279-1d456780-f691-11ea-94d5-e5d0cc299d7c.png">

WIPWIP!

**Comment by ItsJonQ** [comment]
I think I've figured out the Component structure API!

The challenge is that this (generic) ListGroup must accommodate varying control types (sliders, switches, text inputs, etc...). There are some **common** patterns though for ListGroup usage, such as:

* Header (title + potential action)
* Spacing between items (potentially rendering a separator)
* Footer (caption / help text for section)

With how Gutenberg is evolving, controls will most likely need to be enabled or disabled based on configs.
Therefore, the layout components must account for this - whether it's side margins, bottom margin zero'ing, or grid gaps.

Thankfully, we have some of this stuff figured out with `Grid`, `HStack`, and `VStack`.

## Demo

Below is a demo for how a mixture of controls can be grouped, sectioned, and enabled/disabled at will. The margin/spacing between controls maintain the "rules" determined by G2's grid/spacing systems.

![2020-09-15 17-33-38 2020-09-15 17_34_15](https://user-images.githubusercontent.com/2322354/93267802-2fe79b80-f77a-11ea-85d9-d95dc99be1e9.gif)

### Code

Here's the exciting me (for me at least, haha), check out the code:

```jsx
<ListGroup>
  <ListGroupHeader>Title</ListGroupHeader>
  <FormGroup label="Some Field">
    <TextInput />
  </FormGroup>
  <FormGroup label="Another Field">
    <TextInput />
  </FormGroup>
</ListGroup>
```

A cluster using a `Grid` may look like this:

```jsx
<ListGroup>
  <ListGroupHeader>Title</ListGroupHeader>
  <Grid>
    <Select prefix={<Icon />} />
    <Select prefix={<Icon />} />
    <FormGroup label="Some Field">
      <Switch />
    </FormGroup>
  </Grid>
</ListGroup>
```

Here they are combined:

```jsx
<ListGroups>
  <ListGroup>
    <ListGroupHeader>Title</ListGroupHeader>
    <FormGroup label="Some Field">
      <TextInput />
    </FormGroup>
    <FormGroup label="Another Field">
      <TextInput />
    </FormGroup>
  </ListGroup>

  <ListGroup>
    <ListGroupHeader>Title</ListGroupHeader>
    <Grid>
      <Select prefix={<Icon />} />
      <Select prefix={<Icon />} />
      <FormGroup label="Some Field">
        <Switch />
      </FormGroup>
    </Grid>
  </ListGroup>
</ListGroups>
```

Notice the `ListGroups` wrapper

#### Header + Action

There may be a case where the Header title may be accompanied by an action (right side).

The code to do this is also quite simple!

```jsx
<ListGroup>
  <ListGroupHeader>
    Title
    <Button size="small">Edit</Button>
  </ListGroupHeader>
  <Grid>
    ...
  </Grid>
</ListGroup>
```

## Context Is King

Certain components that render under `ListGroup` needed to adjust their behaviour (e.g. spacing). This was all achieved using G2's **Context System**, **not** arbitrary CSS targeting (although the principles are similar).

This is an important distinction.

Components can gain "**awareness**" based on where they're placed, and adapt their **functionality** accordingly.

This is very different compared to CSS where...

HTML elements can gain **style rules** based on where they're placed, and adapt their **aesthetics** accordingly.

A `ListGroupHeader` **knows** it's inside of a `ListGroup`, and is placed accordingly.
If a `Grid` is rendered as a child within `ListGroup`, it's gap spacing is tweaked, (without affecting potential child `Grid` components).

**Comment by ItsJonQ** [comment]
Unnecessary, but nice to know that it's possible 😉 

![2020-09-16 09-53-30 2020-09-16 09_53_55](https://user-images.githubusercontent.com/2322354/93347065-a7f9a400-f802-11ea-95fc-e9b011a687c7.gif)

(Achieved by using the `Animated` component to wrap the items, and using `auto layout`)

**Comment by ItsJonQ** [comment]
🍐 'ed with @noahshrader  this afternoon on refining the layout/spacing for various controls (e.g. links, switches, etc...)
Also tested out a hypothetical design if the background happened to be a dimmer shade.

I think we're getting really close in terms of how all of these pieces come together (both in design and component API).
We also tested out drastically changing behaviour on mobile vs desktop, which can be easily done with G2's responsive system.

Below is a screenshot of some control clusters.

<img width="821" alt="Screen Shot 2020-09-16 at 5 28 19 PM" src="https://user-images.githubusercontent.com/2322354/93394307-07c36f80-f842-11ea-9ac2-a182a45473c5.png">

**Comment by ItsJonQ** [comment]
Lol.. need to fix the rendering of "Surface" for dark mode.

Need to figure out when/if a `Surface` background should render for a `ListGroup` 🤔 
This isn't apparent in light mode, as the backgrounds are the same (white).

<img width="319" alt="Screen Shot 2020-09-16 at 5 38 41 PM" src="https://user-images.githubusercontent.com/2322354/93395214-810f9200-f843-11ea-84f8-84d215523398.png">

**Comment by ItsJonQ** [comment]
Updates! Started exploring how Color-based controls could be clustered and layered within a Sidebar like experience.

---

Designs were based/inspired by work by folks like @jasmussen + @noahshrader  🙇 

---

I've recorded a screen capture video on the prototype I have!
https://d.pr/v/ph28Ql

<img width="882" alt="Screen Shot 2020-09-17 at 5 01 33 PM" src="https://user-images.githubusercontent.com/2322354/93527848-73bbdb80-f907-11ea-92e4-f0b19337a1d5.png">

Above is a screenshot of that prototype. On the left, there are a couple of couples to test out variations of the UI.
On the right, would be the simulated sidebar with the color controls.

There are still some unanswered questions, like... how would we handle A BUNCH of colours?

<img width="819" alt="Screen Shot 2020-09-17 at 5 03 36 PM" src="https://user-images.githubusercontent.com/2322354/93528064-c72e2980-f907-11ea-9ec3-0e5ef67f9373.png">

There may be something to this layering effect.


Prototype can be found here:
https://g2-components.xyz/iframe.html?id=examples-wip-contextpopover--default&viewMode=story

Note: The recent work with `ListGroup` (earlier in this thread) helped this effort **tremendously**.
It's not immediately visible in the rendered UI. It's something that's felt code-side.

**Comment by jasmussen** [comment]
As a prototype, I feel like this definitely suggests the "dim adjacent" feels sufficient. Also, that's a lot of colors in the test, which suggests a scrolling popover — a scrolling popover inside a sidebar that may also be scrolling would be a really bad experience, which I also feel suggests that opening these inline feels right.

**Comment by ItsJonQ** [comment]
Marking this as complete! We're able to achieve these layout structures with `ListGroup`, `Grid`, and the Stack components
