### ISSUE TITLE
Design: Controls (Inputs, SegmentedControls, Buttons, etc...)

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#5]
The UI components are starting to come together, powered by the various (WIP) [core systems](https://github.com/ItsJonQ/g2/issues/3).

For this issue, I would like to touch upon the various control elements (like Inputs, Buttons, etc...).

These components are arguably the **most important elements** within a digital user-interface. Even more so it used within an application like an editor (e.g. Gutenberg).

Not only should they work well in isolation, they should work well when combined together.

## Clusters

Within the context of an editor, a "cluster" of controls  will be common place (example below):

![controls](https://user-images.githubusercontent.com/2322354/88726534-e83e7f00-d0fb-11ea-8e02-9e326fd03512.gif)

(GIF: Shows `TextInput` and `SegmentedControl` components being combined together. Also, dark mode!)

## Controlling Noise

From my experiments, I've realized how important it is to (pardon the pun) "control" visual noise. This becomes especially important depending upon how many "clusters" of controls a user may see on screen, and, how many of those controls require immediate attention.

### High Contrast

<img width="278" alt="Screen Shot 2020-07-28 at 6 04 27 PM" src="https://user-images.githubusercontent.com/2322354/88727141-022c9180-d0fd-11ea-9f43-d4b14cd45770.png">

Above is a "high-contrast" example. Here, the controls have a strong border radius. The pro of this is that controls are easily spotted. However, they become visually overwhelming (and noisy) as soon as they cluster.

### Medium Contrast

<img width="279" alt="Screen Shot 2020-07-28 at 6 04 54 PM" src="https://user-images.githubusercontent.com/2322354/88727253-3d2ec500-d0fd-11ea-8d4d-45757a6bbe40.png">

Above is "medium-contrast". This example is more common place. The borders are present, but are subtle. This is probably the most balance between the 3 examples.

### Low Contrast

<img width="280" alt="Screen Shot 2020-07-28 at 6 05 01 PM" src="https://user-images.githubusercontent.com/2322354/88727345-7404db00-d0fd-11ea-9f01-dd29ecd8e742.png">

Above is "low-contrast". There are no borders at all. These UI controls are common in Mac OS/iOS interfaces. This excels at blending into the background when the controls are not needed. However, the lack of border and controls may make these elements appear disabled (depending on previous user experience)

### Zero Contrast

<img width="235" alt="Screen Shot 2020-07-28 at 8 43 35 PM" src="https://user-images.githubusercontent.com/2322354/88743614-18454c80-d113-11ea-8c38-5df2a716c406.png">

Above is "zero-contrast". There's no indication of interaction at all! (This is from Figma by the way). Borders appear when hovered. Similar to low contrast, this excels at fading into the background, allowing the content to be the main focus. A downside is that a lack of borders may make these controls appear to be non-interactable (like read-only text or labels).

**Comment by ItsJonQ** [comment]
Moar clusters.

<img width="286" alt="Screen Shot 2020-07-28 at 6 42 25 PM" src="https://user-images.githubusercontent.com/2322354/88729521-1c1ca300-d102-11ea-9199-6d7cb4deca51.png">

**Comment by ItsJonQ** [comment]
cc'ing @jasmussen + @MichaelArestad . In case you folks are interested :)

**Comment by ItsJonQ** [comment]
Created a CodeSandbox with a cluster of controls :)

https://codesandbox.io/s/wp-g2-yo5gp?file=/src/App.js

Preview URL:
https://yo5gp.csb.app/

**Comment by jasmussen** [comment]
It's impressive to see you work, Q.

I wonder whether it's the right approach to branch the control appearance into three separate levels of contrast, ultimately asking for a user choice. A high contrast (7:1 ratio AAA) is an awesome addition. But outside of that there's a simplicity in not having to make a choice.

In this case, the low contrast option also adds a lot of gray to the sidebar, which in total volume ends up standing out, for example when compared to Figma where a similar gray means "toggled".

The challenge is real, however! There are many settings already, and with global styles slowly emerging, not only will there be more, but in many cases there will also be presets to choose from and custom values to override. Finding order in this chaos is a key value!

In some casual explorations where I tried to balance this standoff of minimalism, contrast, and global styles, I arrived at "one row per setting", which expands when you click it:

<img width="1026" alt="Typography" src="https://user-images.githubusercontent.com/1204802/90239577-0ad4d580-de28-11ea-8c00-f9660f0650b0.png">

<img width="1277" alt="Color controls" src="https://user-images.githubusercontent.com/1204802/90239582-0d372f80-de28-11ea-9201-c778d6d8156a.png">

I don't totally love the whole flow there, but it gives a rhythm to each row, and it allows expanding the complexity while still having a useful clear resting state. Sharing here in case it can inspire work!

**Comment by ItsJonQ** [comment]
@jasmussen yes! Reducing noise with by hiding settings via popover or collapsible elements would be handy.

The above look like a fine set of UI to prototype from to get a feel for things.

If we see a useful pattern emerge, we can create the component so that folks can easy recreate the same experiences with little code ✌️

**Comment by ItsJonQ** [comment]
Closing this up! We've refined these controls a lot. The individual controls themselves (e.g. `TextInput`) as well as the Layout components designed to contain them (e.g. `Grid`)
