### ISSUE TITLE
Component: Accordion

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#55]
Need to add an `Accordion` component (thanks for the heads up @paaljoachim)!

We already have `Collapsible` and  `Panel` components that could help with this.

`Collapsible` is the primitive that handles the collapsible state + animations. `Panel` a rendered UI layout component that would be used in places like the sidebar (using `Collapsible` underneath).

I gave this one some thought 🤔 

`Panel` gets us 90% of the way there. The issue is that it doesn't synchronize state across multiple `Panel` components. In other words, if there are **3**, only **1** should be allowed to be open at a given time.

See this example:
https://github.com/WordPress/gutenberg/issues/21584#issuecomment-695775809

At the moment, individual `Panel` open and close as they please.

### Component API

We could add a new component like this:

```jsx
<Accordions>
    <Accordion>
        <AccordionHeader>...</AccordionHeader>
        ...
    </Accordion>
</Accordions>
```

Or!! Maybe we can leverage existing `Collapsible` and `Panel` components, and do something like this!

```jsx
<Accordion>
    <Panel>
        ...
    </Panel>
    <Panel>
        ...
    </Panel>
</Accordion>
```

Any `Collapsible` or `Panel` component placed within `Accordion` can have their states synced in the "only 1 can be open" kind of manner.

This "one" or "any" behaviour can also be customized at the `<Accordion />` level via props.

**Comment by paaljoachim** [comment]
Will this in any way help the discussion going on here:
https://github.com/WordPress/gutenberg/issues/21584

The discussion going in JS on the frontend vs using details HTML tag that is not accessible. See the various bottom comments.
