### ISSUE TITLE
Optimizing render performance

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#57]
I'm noticing some sluggishness when there are many list entries with (complex) individual list items **and** if values need to rapidly update.

Might be able to improve render performance by optimizing how components like `Flex` enhance (clone) and render children. Perhaps something can be done with the Context mechanic (`connect` and `ComponentProvider`)

**Comment by ItsJonQ** [comment]
Perhaps we can draw some inspiration from Reakit for context handling:
https://github.com/reakit/reakit/issues/745

**Comment by ItsJonQ** [comment]
I just recorded a screencast where I share some ideas regarding performance as it relates to Design Tools + Gutenberg:

https://www.loom.com/share/c47612ce350b4584acd23493a44acf64

**Comment by ItsJonQ** [comment]
Update!~ I just did a test that pushes interaction and cross-component prop/state interpolation. Results are very promising!

In other words... I did a test that made the UI update A BUNCH, and it's **fast**!!!!

## Demo

[**Video Demo**](https://d.pr/i/XnZ00n)
[**Video screencast + overview**](https://www.loom.com/share/e6cbb16ee80e47139a2478214714f592)

The demo simulates the data-binding relationships within Gutenberg. Specifically:

`wp-data` 👈 👉 Block controls
👇
Editor ("Canvas")

Larger components, basically any "Design Tool" as well as feature rich base level components, have to manage both inner state and sync incoming state (from props).

Achieving this is already quite challenging... even more so when rapid-fire updates need to be supported.

G2 Components accomplish this with mindful memoization and alternative state management techniques (via [Zustand](https://github.com/pmndrs/zustand))

The demo showcases these rapid-fire updates happening very smoothly without dropping frames.

Try it for yourself ✌️ :
https://g2-components.xyz/iframe.html?id=designtools-dataflow--default&viewMode=story

You can enable auto updating by adjusting the value under "Autopilot".

Drilling into some charts...

These are the performance results at level **11** speeds:

<img width="314" alt="Screen Shot 2020-10-07 at 2 34 42 PM" src="https://user-images.githubusercontent.com/2322354/95372948-4630d500-08aa-11eb-8b51-e8a42337ee24.png">

State consolidation + rendering happens comfortably within the 16.666ms windows.
This allows for the UI to render lag free 🎉

**Comment by ItsJonQ** [comment]
Here's a fun update...

This gets into the nitty gritty! I had a thought yesterday of a perf. improvement that could be made in the core level G2 components (e.g. `Text`, `Flex`, `Grid`, etc...). Common components that would be used everywhere, with the potential of re-rendering a lot.

### 💡The Idea

> What if we memoized the certain `css()` function calls for dynamic styles...

The idea is that it would save Emotion having to dip into it's memoized cache.

### 📊 Results

I ran the DataFlow story in Autopilot mode to maximum UI stress load. This is a development build of React, which means that it'll be slower (which is good for perf testing).

There's A LOT going on in the screenshot below.

#### Top

Current G2 components.

#### Bottom

Perf improvements.

<img width="1479" alt="Screen Shot 2020-10-09 at 1 05 22 PM" src="https://user-images.githubusercontent.com/2322354/95611808-570b5300-0a30-11eb-8418-d936fa9ec43d.png">


There differences are subtle... but notice the top left hand corner.

Using this memoization technique reduces frame drops by **5%**.

In reality, this change wouldn't really be noticeable. However, I believe that these Components (or any UI components) should be optimized as much as possible to reduce the burden on the consumer.

Shaving off `0.16ms` of computation time per render of a G2 component "cluster" means that that precious power can be allocated to other things (like the Gutenberg editor content).

**Comment by ItsJonQ** [comment]
Update: With some fine tuning.. we have a **+6%** improvement!

Consistent frame rate (higher is better)
64% -> 69% -> **75%**

Development build. Same DataFlow test. Level 11 speeds.

<img width="1907" alt="Screen Shot 2020-10-10 at 12 58 31 PM" src="https://user-images.githubusercontent.com/2322354/95660826-86859280-0af8-11eb-8e63-e8c184f3fc4f.png">

Notice there's much less angry red flags on the right hand side!~

**Comment by ItsJonQ** [comment]
## ⛈ Super Hard Performance Test (New)

I added a new **incredibly UI taxing** performance test.

Every value change triggers a re-rendering + calculation for 150 items that render randomly as stripes.
These stripes are (intentionally) rendered using common real world techniques (which isn't nearly as fast as what React/JS is capable of).

As far as I know, it's **impossible** to render a smooth 60fps given this test case (again, the elements are intentionally rendered sub-optimally).

<img width="1439" alt="Screen Shot 2020-10-10 at 4 18 07 PM" src="https://user-images.githubusercontent.com/2322354/95664302-80051400-0b14-11eb-85a6-7e4d7db5ba1b.png">

**The test can be found here**
https://g2-components.xyz/iframe.html?id=designtools-performancetest--default&viewMode=story

⚠️ Just a heads up: I've placed a warning at the top of the page due to the visual flashing nature of the test.

---

The test was inspired by react-spring / zustand:
https://codesandbox.io/s/peaceful-johnson-txtws

They're able to achieve 60fps using an alternative render technique that bypasses React's render cycle.

**Comment by ItsJonQ** [comment]
### 🍯 Bonus Update

Because G2's style system doesn't use React/Context for it's variables or it's modes... it is **ultra** performant.
For example, switching from light to dark mode doesn't require React to go through it's diff'ing process!

Try it for yourself. Run the test and change light/dark modes:

<img width="509" alt="Screen Shot 2020-10-10 at 6 16 12 PM" src="https://user-images.githubusercontent.com/2322354/95666112-b77bbc80-0b24-11eb-865a-2e1d3545e3d9.png">

The individual stripes are G2 `<View />` components by the way, and are using a G2 style system variable for their background colour.

I believe performing the same task would be much more taxing for other systems that rely on context for theming 🤔

**Comment by ItsJonQ** [comment]
## ⚖️ Comparing Libraries

I just added 2 new performance tests using the [initial one](https://g2-components.xyz/iframe.html?id=designtools-performancetest--default&viewMode=story) as the "control".

These 2 new tests have the exact same setup. However... they use different UI libraries!

One is [Shopify Polaris](https://github.com/Shopify/polaris-react/tree/master/src/components), the other is [Material UI](https://material-ui.com/).

Below are screenshots of the results.

Running "Autopilot". Leaving it running for a bit. Screenshot'ing the average FPS.

### G2

**72% frames preserved**

<img width="1900" alt="Screen Shot 2020-10-10 at 10 24 38 PM" src="https://user-images.githubusercontent.com/2322354/95668866-692be500-0b47-11eb-9757-952655749994.png">

### Polaris

**68% frames preserved**

<img width="1899" alt="Screen Shot 2020-10-10 at 10 18 45 PM" src="https://user-images.githubusercontent.com/2322354/95668854-4699cc00-0b47-11eb-86a2-9809923dd3d9.png">


### Material UI

**71% frames preserved**

<img width="1904" alt="Screen Shot 2020-10-10 at 10 19 10 PM" src="https://user-images.githubusercontent.com/2322354/95668857-4f8a9d80-0b47-11eb-885e-c787e7bef2fc.png">

They're all **very** close. The differences my be **negligible**.

There are some interesting difference. At least, in terms of how the UI "feels" to interact with.

## ✨ UI Feels

I tested the various pieces by attempting to interact with them as quickly as possible. For example, spamming letters into the search input (by holding a letter down).

### Autopilot OFF

I performed these actions with Autopilot turned **OFF**.

#### G2

* SearchInput: **Fast**
* Sliders: **Fast**
* NumberInput: **Fast**

#### Polaris

* SearchInput: **Fast**
* Sliders: **Fast**
* NumberInput: **Fast**

#### Material UI

* SearchInput: **Fast'ish**
* Sliders: **Fast'ish**
* NumberInput: **Fast'ish**

### Autopilot ON

I performed these actions with Autopilot turned **OFF**.
I excluded the SearchInput and NumberInput as it was impossible in interact with those with autopilot on.

#### G2

* Sliders: **Fast**

#### Polaris

* Sliders: **Fast**

#### Material UI

* Sliders: **Slow**

Overall, G2 and Polaris feel very similar.
There's a sliver of jerkiness with Material UI compared to the other libraries.

## 💅  Differences in CSS Architectures

Aesthetics aside, there are fundamental differences between the various UI libraries.

### Polaris

Polaris is probably the "lightest" compared to G2 and Material UI. Polaris relies on an external stylesheet for CSS, whereas the other libraries use a CSS-in-JS solution. As such, Polaris is missing CSS-in-JS features like the polymorphic base "Box" component and JS powered/controlled styles.

### Material UI

Material uses [JSS](https://cssinjs.org/) for their CSS-in-JS solution. This strategy relies on provider/consumers for their styled components in order to use theme settings and variables.

### G2

G2 uses a custom [Emotion configuration](https://github.com/ItsJonQ/g2/tree/master/packages/create-styles). Theming and variables are ultimately compiled as CSS variables, bypassing the need for provider/consumers like more traditional CSS-in-JS techniques.

## ✨ Thoughts

I'm excited to see that the G2 components can perform admirably against these UI libraries. Matching their performance in terms of **throughput** as well as user **interaction** and **feel**. Not only that, it's able to do it while preserving it's style system features.

From a polymorphic Box (`View` in G2), to inline `css` prop rendering, to provider-less style injection, to mode support (e.g. dark), and theming.

**Comment by diegohaz** [comment]
@ItsJonQ you're on fire! Great work! 👏

I wonder if using `Object.assign` instead of object spread has any impact on performance. From the initial tests I did, using `Object.assign` directly would make things 10-20% faster.

But when I [applied it to Reakit](https://github.com/reakit/reakit/pull/738), I noticed that it actually made things a little bit slower. I don't know if it was because I was making it through the Babel plugin, and not directly using `Object.assign` like in my tests, but this shouldn't make any difference. 🤔

The interesting thing is that the JSX Babel transform uses `Object.assign` by default when you spread props, and this was making it perform a little better than hooks with spread props (in my tests, but I couldn't confirm it in Reakit).

**Comment by ItsJonQ** [comment]
@diegohaz Thank you <3!

> I wonder if using Object.assign instead of object spread has any impact on performance.

I'm not sure either 🤔 . I wanted to try it out based on your findings. I just ran some tests, with `Object.assign` vs `{...spread}`.

Assign vs Spread.

PerformanceTest story. Pressing `tick` 10 times. Once every second.

<img width="1553" alt="Screen Shot 2020-10-11 at 9 34 22 AM" src="https://user-images.githubusercontent.com/2322354/95680083-f7828400-0ba4-11eb-8d6c-72c87685dfb3.png">

I honestly can't see a difference in their performance 😂 .

For the sake of making the component layer code easier to work with, I think I'm going to use `{...spread}`.

**Comment by ItsJonQ** [comment]
Closing this for now! The investigation (above) has been very fruitful. It's led to several architectural changes within G2 Components, such as mindful memoization, reducing component layers, leveraging hooks, and using [substate](https://github.com/ItsJonQ/g2/tree/master/packages/substate), and more. All of these enhancements work together to provide a seamless performance boost for consumers, out of the box!
