### ISSUE TITLE
Bug: Configure settings

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#59]
From @diegohaz 

> The slider issue is happening on master, but the PR I sent has another bug. After interacting with the configure popover, the shadows popover values will temporarily reset to their initial value

**Comment by ItsJonQ** [comment]
Update: I believe there's something with the Reakit Backdrop component that's "absorbing" mouse events.
It's something I've noticed before and ran into recently 🤔

**Comment by diegohaz** [comment]
Does it happen with `reakit@next`?

**Comment by ItsJonQ** [comment]
@diegohaz Good question! Lemme check 🎉

**Comment by ItsJonQ** [comment]
@diegohaz Yup! I'm using `reakit@next`.

I created a demo for you <3

![Screen Capture on 2020-10-07 at 15-08-50](https://user-images.githubusercontent.com/2322354/95376484-294ad080-08af-11eb-8843-0c676ef22fc6.gif)

The purple RK ball follows my cursor on `mousemove`.
However, it stops once I open a popover.

Here's a link to the demo:
http://g2-components.xyz/iframe.html?id=designtools-reakit-test--default&viewMode=story

Story source code:
https://github.com/ItsJonQ/g2/blob/master/packages/design-tools/src/__stories__/Reakit.stories.js

Popover code:
https://github.com/ItsJonQ/g2/blob/master/packages/components/src/Popover/Popover.js

With the exception of keeping `popover` state in context.. I don't think I'm doing anything too over the top with Reakit Popover 🤔

**Comment by diegohaz** [comment]
Oh okay! That's actually expected. Since the popover has `modal` set to `true`, you're not supposed to interact with content behind it (so `mousemove` is blocked outside of the popover). I guess the configure popover should have `modal` set to `false` or close when interacting with the page.

**Comment by diegohaz** [comment]
`modal={true} hideOnClickOutside={false}` is likely an invalid state. I don't know if there's a valid use case for this.

**Comment by ItsJonQ** [comment]
@diegohaz Ohh! Interesting. Thank you 🙏 

> modal={true} hideOnClickOutside={false} is likely an invalid state. I don't know if there's a valid use case for this.

Ultimately, what I wanted was for the Popover to be Portal'ed and the ability to keep it open as you click outside.

A use case would be popovers in apps like Figma:

<img width="613" alt="Screen Shot 2020-10-07 at 3 26 25 PM" src="https://user-images.githubusercontent.com/2322354/95378164-83e52c00-08b1-11eb-8cc0-79ad5e8af6fe.png">

For example, you can engage with the canvas content as the Color tools stay open.

**Comment by diegohaz** [comment]
> Ultimately, what I wanted was for the Popover to be Portal'ed and the ability to keep it open as you click outside.

Cool! So you just want `Portal`, like in this example: https://reakit.io/docs/dialog/#chat-dialog

Maybe Reakit should show a warning when `modal={true} hideOnClickOutside={false}` is used. It's likely people just want `Portal`, not `modal`.

Still, I believe there's a bug related to this code: https://github.com/reakit/reakit/blob/bf9a795921d07c4a39e7c8a9ca67c879441d69d2/packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts#L40-L46

(just leaving here for future reference as I don't have time to dig into this right now)

**Comment by ItsJonQ** [comment]
Amazing!! Thank you 🙏 !!!!!!

I think your Chat Dialog example was exactly what I needed

**Comment by ItsJonQ** [comment]
Issue resolved, thanks to @diegohaz 's suggestion
