### ISSUE TITLE
Component: PresetInput + UnitInput

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#66]
A couple of interesting components have emerged from the **Typography Tool** prototypes:
https://github.com/ItsJonQ/g2/issues/65

<img src="https://user-images.githubusercontent.com/2322354/96319870-d1af1200-0fde-11eb-84b8-820599e7b83c.gif" width="300" />

(GIF: Demo'ing the `PresetInput`)

The `UnitInput` and `PresetInput` (which uses `UnitInput` under the hood).

We're not sure if they are the correct/final designs (as far as UI, UX, and interactions are concerned), but they're incredibly promising!

There were several **breakthroughs** in prototyping and designing this component!

**Link to Demo**
https://g2-components.xyz/iframe.html?id=designtools-typographytools--plus-minus-inline-truncate&viewMode=story

Note: These components aren't perfect... However, they work well enough to help test out and validate UI/interaction ideas.

### 🚗 Powerfully Compact

This single input does **a lot**! It's really interesting to see a bunch of features (below) compacted into a single multi-purpose interface. Especially if this interface is to be used in many many places (as Design Tools evolve and improve)

Features include:

* Unit parsing
* Unit selection
* Preset selection
* Typeahead: Autofill for preset
* Typeahead: Autofill for units
* Drag to change
* Step "jumping" (when holding `shift`)

Figuring out how to even construct this UI and handle the events has been an interesting challenge!

### ✅ CSS Prop Validation

Fun UI aside, we think this is one of the biggest insights! We figured out a way to validate if a [value works for a specific CSS property](https://github.com/ItsJonQ/g2/blob/master/packages/utils/src/unitValues.js#L20).

Value validation (and reset handling) will be **incredibly important** in the Design Tool layer, especially as more controls get added that (ultimately) render out CSS style properties.

For example, let's say we want check for the `height` CSS property.

It can accept a wide range of very similar values:

`10px`, `auto`, `5vh`, `0`, etc...

The tricky thing with values like `0` is that it could be a number (`0`) or a string (`"0"`).

As you can see... lots of variations.

To throw wrench (🔧 ) into everything... negative values are acceptable CSS values... **but not for height**.

(omg... what about things like `calc`? Maybe we can ignore `calc` for now... but still!)

This validation technique takes care of it in a **reliable** way, using the browsers CSS's engine under the hood.
Not quite [CSS Typed Object Model](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Typed_OM_API)... but close (and compatible with browsers).

This has been built into `UnitInput`, with a component API that looks like this:

```jsx
<UnitInput value={value} onChange={handleOnChange} cssProp="height" />
```

Passing in the (camelCased) cssProp adds the validation step for you! ❤️ 

### ⏪ Change, Reset, and Overall Value Handling

At the moment, value serialization + reset handling is quite tricky in Gutenberg. It is often hard-coded ad-hoc logic, which is difficult to repurpose. We're starting to move some of this into the component/design tool layer, which is great.

I believe this should be the direction we should be going in 🙌 .

That means the low level components (like a base `TextInput`) must have support for multi-state changes (like reseting a value) in addition to providing the ability to adjust the value (like `10` to `10px`) as it is "processed" for that final `onChange` send-off.

After that, larger components (like `UnitControl`) and Design Tools can create, enhance, and extend functionality on top.

Ultimately, this would mean that a lot of the common fiddly (very fiddly) logic will be abstracted away into the components/tools layer, allowing for Gutenberg Block components (e.g. `core/cover`) to be MUCH more streamlined - allowing for a greater focus on rendering into the page/site, rather than managing `attribute` changes.

**Comment by ItsJonQ** [comment]
☝️ That being said... There are still things we aren't sure of for the `UnitInput`.

I feel like interactions for accepting/rejecting the type-ahead value can be better.

I draw a rough interaction for between states.
It currently has **some** of these actions.

![IMG_6344 2](https://user-images.githubusercontent.com/2322354/96323810-c8c53d00-0fec-11eb-91ba-43ea21f49abf.jpeg)

Things to think about!

**Comment by ItsJonQ** [comment]
Pretty neat how it works on mobile/tablets,

![35A34EFC-0F2D-408C-AD06-C8B5B54FC83C](https://user-images.githubusercontent.com/2322354/96325021-bc43e300-0ff2-11eb-858a-8bede1825430.png)

Need to add touch event support for improved focus/text selection interactions

**Comment by ItsJonQ** [comment]
I've implemented a new `UnitInput`!

Going to table `PresetInput` for now. The reason is because there were still some fine-grain interaction/usability issues.

**Comment by aristath** [comment]
(coming from https://github.com/WordPress/gutenberg/pull/25988) Is there a way we can port this to Gutenberg prior to the whole G2-migration? The current `UnitControl` there is extremely flawed... and this is just amazing, could be used in soooo many places, from column-widths to font-sizes and everything in between

**Comment by ItsJonQ** [comment]
@aristath Thank you for your warm + supportive comments 🙏 

> Is there a way we can port this to Gutenberg prior to the whole G2-migration?

Mayyyyyyyyybe, but not likely. The majority of the code happens within hooks/functions, which doesn't necessarily depend on things like the Style system. In theory, those can be brought over. (However, it requires some other parts of G2, like the `substate` and `utils` packages).

> The current UnitControl there is extremely flawed

My bad 🙈 . I learned a lot from creating `UnitControl`. The V1 if you will.

It was only recently that I really "cracked" the code by figuring out the different "stages" of handling state, and relying on an alternative + optimized [state management strategy](https://github.com/ItsJonQ/g2/tree/master/packages/substate).

This really helped add stability to the unit parsing feature. Not only that, but it made it trivial to help the control understand values like `calc()` and even `var()`:

https://github.com/ItsJonQ/g2/pull/80

Like you had touched upon... I believe the `UnitInput` will be the most **commonly** used and most **important** UI element to be part of the Global Styles/FSE experience.
