### ISSUE TITLE
Adding a design controls G2 option into the experiments screen in the Gutenberg plugin.

### ISSUE THREAD

**Issue by paaljoachim** [ItsJonQ/g2#69]
Hey Jon

What about adding an option into the Gutenberg -> Experiments screen to enable testing out G2 design control components directly in the Gutenberg plugin? As it would be a way to do some real life testing of various controls made with G2. I ask because you show so many awesome examples that I look forward to testing out in a real situation. Example typography controls. Having the experimental option inside the plugin will also give a good opportunity to get additional feedback.

Thanks!

**Comment by ItsJonQ** [comment]
Heya @paaljoachim ,

Interesting idea! It would be a good way to poke at the G2 Components in the project.

I'm not sure that's feasible at the moment (I may be wrong).

The G2 Components code isn't a theme/skin, that means we'd need to rebuild/replicate the existing controls with the components.

Maybe that's okay to start?

Sidenote: I'm preparing G2 to get a more formal proposal/PR for Gutenberg soon! We'll see how it plays out :)

**Comment by paaljoachim** [comment]
The formal approach sounds like the best way to proceed. 
Then see how things happen from there.

I will close this issue for now, and if it natural to do so we can always reopen.
