### ISSUE TITLE
ColorPicker: react-colorful Library

### ISSUE THREAD

**Issue by omgovich** [ItsJonQ/g2#71]
Hi! My name is Vlad and I'm a creator of `react-colorful`.
I'm so surprised about how your project uses our component 👍 Hope you like it.

Just wanted to say two things:
1. Let me know if you need any help or you have issues with `react-colorful`.
2. We're [working](https://github.com/omgovich/react-colorful/pull/87) on a simple CSS-in-JS solution. It means that soon there will be no need to copy our styles. I let you know as soon as it will be ready.

Regards,
Vlad

**Comment by ItsJonQ** [comment]
Heya @omgovich ,

Sounds good! Excited to see how it goes :).
Just a heads up, depending on how your CSS-in-JS solution works... we may have to do a custom implementation anyway.

Our Style System does use Emotion. However it's an enhanced version, created from `create-emotion`, rather than using `emotion/styled` or `emotion` or `emotion/core`.

**Comment by ItsJonQ** [comment]
Closing this for now.

Updated `react-colorful` to the latest `4.4.4`.
With some adjustments, it's working quite well.

https://github.com/ItsJonQ/g2/pull/235

**Comment by omgovich** [comment]
Hey @ItsJonQ! Hope you're doing well. 

I have news for you:
react-colorful v5 was just released and it's 100% CSS-in-JS — doesn't require importing CSS-file.

It means that you can remove all CSS code you copied from the original repo.

**Comment by ItsJonQ** [comment]
@omgovich Thanks for the heads up! I took a look at the V5 update. I don't have experience with `parcel-plugin-css-to-string`, so I'm unsure how it would work with our current styling solution.

I guess we'll find out when we continue work on the ColorPicker :)

**Comment by omgovich** [comment]
@ItsJonQ you don't need to work with `parcel-plugin-css-to-string` — that is an internal tool I use to bundle my website.
To have the new version working it's enough to run `npm install react-colorful@^5.0.0`.
The new picker injects all of its styles automatically and works with any CSS-in-JS solution.

Here is for example demo of how it works with Emotion:
https://codesandbox.io/s/react-colorful-emotion-t0df3?file=/src/MyPicker.js

**Comment by omgovich** [comment]
That all you need to do for having a properly rendered color picker (with my default styles):

```jsx
import { HexColorPicker } from "react-colorful";

<HexColorPicker />
```

Then override styles with your own stylesheet to personalize the picker.
