### ISSUE TITLE
i18n System

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#83]
Initially, I thought that we could just use the `@wordpress/i18n` package as the i18n system for G2 Components.

However, it looks like there may be some sub-optimal implementation details with it 🤔 

@jsnajdr wrote about it in more detail here:
https://github.com/WordPress/gutenberg/issues/19210

Perhaps G2 can offer a space to explore how we can improve it?
Maybe creating a library built on top of WP i18n. Something that seamlessly uses a Context-based strategy.

**Comment by jsnajdr** [comment]
> Maybe creating a library built on top of WP i18n. Something that seamlessly uses a Context-based strategy.

Yes, that's exactly what [`@automattic/react-i18n`](https://github.com/Automattic/wp-calypso/tree/master/packages/react-i18n) does. We don't need to create anything new, just transfer the existing library to the Gutenberg repo and use it in G2.

**Comment by ItsJonQ** [comment]
@jsnajdr With this Context/Hook/HOC approach... it doesn't seem like we can do some 1-shot update in Gutenberg right?

Because everything is `import { __ } from '@wordpress/i18n';`

I'm guessing each instance of `__` would need to be refactored to use `const { __ } = useI18n()`.

Not a blocker! Just wanted to confirm :).

Beyond code within Gutenberg.. I believe the `i18n` library is exposed globally in the `wp.` object.
I'm not too sure how we'd upgrade folks who are using that implementation (3rd party block devs) 🤔 .

Maybe we can't? And there will be 2 i18n libraries within Gutenberg moving forward?

**Comment by jsnajdr** [comment]
> I'm guessing each instance of `__` would need to be refactored to use `const { __ } = useI18n()`.

Yes, that's the codemod that needs to be applied to every component to make it use `react-i18n`. I expect there to be a lot of usages that will be tougher than that though.

> Maybe we can't? And there will be 2 i18n libraries within Gutenberg moving forward?

It's not 2 libraries -- `i18n` will continue to be used, just with better React bindings on top of it. `react-i18n` is not an independent implemenation, just an extra reactive/contextual layer between the `i18n` object and your React component.

The script can be enqueued and exposes as `wp.reactI18n`, just like any other Gutenberg library.

Every 3rd party block declares the scripts it depends on. `wp.reactI18n` will be either part of the Gutenberg plugin, or later directly in Core.

Hope that helps 🙂

**Comment by ItsJonQ** [comment]
> Hope that helps 🙂

Indeed it did! Thank you 🙏 .

This sounds like a lovely solution!! ❤️ 

> Yes, that's the codemod that needs to be applied to every component to make it use react-i18n. I expect there to be a lot of usages that will be tougher than that though.

I haven't looked into it yet... but the `__('')` uses I've encountered in core seem pretty straight forward.
Are there any particular use cases where it may be tough?

**Comment by jsnajdr** [comment]
> Are there any particular use cases where it may be tough?

Migrating usages of `__('')` is straightforward only if the usage is directly in the React component, near the `__ = useI18n()` hook call. If the translation is done somewhere outside the component, then we need to ensure that the right `__` instance is passed to it (as a new parameter) and that the translation is re-done when the i18n data change.

For example, a static object:
```js
const statsLabels = {
  'day': __( 'Day' ),
  'week': __( 'Week' ),
  'month': __( 'Month' ),
};
```
needs to become a function:
```js
const getStatsLabels = ( __ ) => ( {
  'day': __( 'Day' ),
  'week': __( 'Week' ),
  'month': __( 'Month' ),
} );
```
Making this work in more complicated scenarios, e.g., when the changed function is several call stack frames away, can be challenging.

The end goal of this entire exercise is to be able to change the locale, or the translation set, in real-time, changed reactively. Something like when you want to change the theme of the entire UI or to switch between light and dark modes with a toggle. In all these cases, it's desirable to have the value somewhere in a context provider at the top and make all the consumers flawlessly react to any change.

**Comment by ItsJonQ** [comment]
> For example, a static object... needs to become a function:

Ah, that makes sense! I remember seeing several cases of static i18n labels in Gutenberg. I can see how that would be trickier.

> The end goal of this entire exercise is to be able to change the locale, or the translation set, in **real-time**, changed **reactively**.

Yes!

**Comment by ItsJonQ** [comment]
@saramarcondes To move this along... let's start using `@automattic/i18n` in G2 - either directly or creating a `@wp-g2/i18n` package (which exports the `@automattic/i18n` package).

Mostly because I'm curious what the code and workflow would be like :).
I don't think we'd need it in many places... mostly for aria/Tooltip labels.

**Comment by saramarcondes** [comment]
@ItsJonQ We can close this now that the #79 is merged as that introduced `@wordpress/i18n`.

We should open a new issue perhaps to retroactively i18n-ify all the existing components that need translations?

**Comment by ItsJonQ** [comment]
@saramarcondes Sounds good!

> We should open a new issue perhaps to retroactively i18n-ify all the existing components that need translations?

Also sounds good :).

After that is done, would we then used `@automattic/i18n`? Or would that perhaps come later when G2 stuff has been moved over to the Gutenberg repo?

**Comment by saramarcondes** [comment]
I say lets use what's currently in Gutenberg which is `@wordpress/i18n` and then we can push the effort forward of using `@automattic/react-i18n` afterwards?

**Comment by ItsJonQ** [comment]
@saramarcondes Sounds good to me. Is that okay @jsnajdr ?

> FWIW I'm not familiar with the process of proposing the new library to core

Me neither. The most substantial one that I proposed was `@emotion/core`
