### ISSUE TITLE
Utils: Is - Type Checker library

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#91]
At the moment, the `is` type checker library is coming from https://github.com/ItsJonQ/is.
It's working okay so far. However, I'd like to be able to check a wider range of types.

### 🧙‍♂️ `@sindresorhus/is`

I'm a big fan of `@sindresorhus/is`:
https://github.com/sindresorhus/is

(The Typescript support is amazing on that btw)

However, this library has a bundle size of approx 10kb (3.1kb gzipped).
That's the only downside that I know of.

Ideally, I feel like this `is` checker should be as tiny as possible.

Perhaps this amount is okay?

### 💨 Lodash

An alternative would be to prepare `lodash`'s type checkers in the `is.type()` like API.

(I swear, the DX for `is.type()` is amazing)

Although G2 doesn't use lodash... The reason I'm suggesting repurposing lodash's type checkers is because Gutenberg uses lodash. In that sense, we wouldn't need to import another library, which would save on bundle size (in theory)

**Comment by saramarcondes** [comment]
Why not just use `lodash` directly? It's already used by Gutenberg so it'd completely remove the additional JS to be bundled. Likewise, the type definitions for `lodash` are comprehensive so the DX is great. To me there's little difference between `_.isNumber()` and `is.number()` from a DX perspective. You get helpful completion either way (`_.is` will fill out with a whole host of type checking methods in intellisense for example).

**Comment by ItsJonQ** [comment]
> Why not just use lodash directly?

That's a fair point! One interesting question.

What if we want to add custom `is` type checking that lodash doesn't support?
I'm not sure what the best way would be to combine that with lodash 🤔 

For example, `_.isNumeric()`, which is truthy for `'3'` (`string`) or `3` (`number`).
Lodash's `_.isNumber()` doesn't support `string` numbers.

I've learned that this is **super** important (and helpful) for complex TextInput values (e.g. CSS property values)

**Comment by saramarcondes** [comment]
Hmmm, understood! In that case a "pass-through" library that mostly just passes through to lodash but augments with a few extra methods seems like a good option rather than re-writing the whole thing (given `lodash`'s battle-tested-ness.
